apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-backend
  template:
    metadata:
      labels:
        app: mern-backend
    spec:
      containers:
      - name: mern-backend
        image: amaltscaria/mern-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: mern-secrets
              key: MONGO_URL
        - name: EMAIL
          valueFrom:
            secretKeyRef:
              name: mern-secrets
              key: EMAIL
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mern-secrets
              key: PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mern-secrets
              key: SECRET_KEY
        - name: RAZORPAY_KEY_ID
          valueFrom:
            secretKeyRef:
              name: mern-secrets
              key: RAZORPAY_KEY_ID
        - name: RAZORPAY_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: mern-secrets
              key: RAZORPAY_KEY_SECRET
        - name: PORT
          value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: mern-backend-service
spec:
  selector:
    app: mern-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
